"""initial schema

Revision ID: 64ccaac06660
Revises:
Create Date: 2026-09-30 04:26:08.870381

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "64ccaac06660"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_execution_logs",
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.Column("agent_id", sa.Uuid(), nullable=True),
        sa.Column("event", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("agent_execution_logs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_agent_execution_logs_agent_id"), ["agent_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_agent_execution_logs_event"), ["event"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_agent_execution_logs_task_id"), ["task_id"], unique=False
        )

    op.create_table(
        "agents",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("model_provider", sa.String(length=32), nullable=False),
        sa.Column("model_name", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("system_prompt", sa.Text(), nullable=True),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("agents", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_agents_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_agents_role"), ["role"], unique=False)
        batch_op.create_index(batch_op.f("ix_agents_status"), ["status"], unique=False)

    op.create_table(
        "connectors",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("configuration", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("connectors", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_connectors_name"), ["name"], unique=True)
        batch_op.create_index(batch_op.f("ix_connectors_type"), ["type"], unique=False)

    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_organizations_name"), ["name"], unique=True)

    op.create_table(
        "users",
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_users_username"), ["username"], unique=True)

    op.create_table(
        "agent_skills",
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("skill_id", sa.String(length=128), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("agent_skills", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_agent_skills_agent_id"), ["agent_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_agent_skills_skill_id"), ["skill_id"], unique=False)

    op.create_table(
        "connector_logs",
        sa.Column("connector_id", sa.Uuid(), nullable=False),
        sa.Column("agent_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=128), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("cost", sa.Float(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["connector_id"], ["connectors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("connector_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_connector_logs_action"), ["action"], unique=False)
        batch_op.create_index(batch_op.f("ix_connector_logs_agent_id"), ["agent_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_connector_logs_connector_id"), ["connector_id"], unique=False
        )

    op.create_table(
        "organization_members",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "user_id", name="uq_organization_member"),
    )
    with op.batch_alter_table("organization_members", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_organization_members_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_organization_members_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "projects",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("repository", sa.String(length=255), nullable=True),
        sa.Column("owner_id", sa.Uuid(), nullable=True),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_projects_name"), ["name"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_projects_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_projects_owner_id"), ["owner_id"], unique=False)

    op.create_table(
        "provider_accounts",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("credential_reference", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "provider", name="uq_provider_account"),
    )
    with op.batch_alter_table("provider_accounts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_provider_accounts_user_id"), ["user_id"], unique=False)

    op.create_table(
        "project_memory",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding", sa.JSON(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("project_memory", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_project_memory_project_id"), ["project_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_project_memory_type"), ["type"], unique=False)

    op.create_table(
        "tasks",
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("cost", sa.Float(), nullable=True),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tasks_project_id"), ["project_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_tasks_status"), ["status"], unique=False)

    op.create_table(
        "virtual_changes",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("file_path", sa.String(length=512), nullable=False),
        sa.Column("original_content", sa.Text(), nullable=False),
        sa.Column("proposed_content", sa.Text(), nullable=False),
        sa.Column("diff", sa.Text(), nullable=True),
        sa.Column("agent_source", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("virtual_changes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_virtual_changes_file_path"), ["file_path"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_virtual_changes_project_id"), ["project_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_virtual_changes_status"), ["status"], unique=False)

    op.create_table(
        "usage_records",
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("cost", sa.Float(), nullable=True),
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.Column("agent_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("usage_records", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_usage_records_agent_id"), ["agent_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_usage_records_model"), ["model"], unique=False)
        batch_op.create_index(batch_op.f("ix_usage_records_provider"), ["provider"], unique=False)
        batch_op.create_index(batch_op.f("ix_usage_records_task_id"), ["task_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("usage_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_usage_records_task_id"))
        batch_op.drop_index(batch_op.f("ix_usage_records_provider"))
        batch_op.drop_index(batch_op.f("ix_usage_records_model"))
        batch_op.drop_index(batch_op.f("ix_usage_records_agent_id"))

    op.drop_table("usage_records")
    with op.batch_alter_table("virtual_changes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_virtual_changes_status"))
        batch_op.drop_index(batch_op.f("ix_virtual_changes_project_id"))
        batch_op.drop_index(batch_op.f("ix_virtual_changes_file_path"))

    op.drop_table("virtual_changes")
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tasks_status"))
        batch_op.drop_index(batch_op.f("ix_tasks_project_id"))

    op.drop_table("tasks")
    with op.batch_alter_table("project_memory", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_project_memory_type"))
        batch_op.drop_index(batch_op.f("ix_project_memory_project_id"))

    op.drop_table("project_memory")
    with op.batch_alter_table("provider_accounts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_provider_accounts_user_id"))

    op.drop_table("provider_accounts")
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_projects_owner_id"))
        batch_op.drop_index(batch_op.f("ix_projects_organization_id"))
        batch_op.drop_index(batch_op.f("ix_projects_name"))

    op.drop_table("projects")
    with op.batch_alter_table("organization_members", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_organization_members_user_id"))
        batch_op.drop_index(batch_op.f("ix_organization_members_organization_id"))

    op.drop_table("organization_members")
    with op.batch_alter_table("connector_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_connector_logs_connector_id"))
        batch_op.drop_index(batch_op.f("ix_connector_logs_agent_id"))
        batch_op.drop_index(batch_op.f("ix_connector_logs_action"))

    op.drop_table("connector_logs")
    with op.batch_alter_table("agent_skills", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agent_skills_skill_id"))
        batch_op.drop_index(batch_op.f("ix_agent_skills_agent_id"))

    op.drop_table("agent_skills")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_organizations_name"))

    op.drop_table("organizations")
    with op.batch_alter_table("connectors", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_connectors_type"))
        batch_op.drop_index(batch_op.f("ix_connectors_name"))

    op.drop_table("connectors")
    with op.batch_alter_table("agents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agents_status"))
        batch_op.drop_index(batch_op.f("ix_agents_role"))
        batch_op.drop_index(batch_op.f("ix_agents_name"))

    op.drop_table("agents")
    with op.batch_alter_table("agent_execution_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agent_execution_logs_task_id"))
        batch_op.drop_index(batch_op.f("ix_agent_execution_logs_event"))
        batch_op.drop_index(batch_op.f("ix_agent_execution_logs_agent_id"))

    op.drop_table("agent_execution_logs")
    # ### end Alembic commands ###
